# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  labels:
    app: api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      nodeSelector:
        type: worker1
      containers:
        - name: api-container
          image: myfirstcontainerdemo.azurecr.io/demok8sapi:v_${{github.run_number}}
          ports:
            - containerPort: 8080

---

# Expose
apiVersion: v1
kind: Service
metadata:
  name: api-expose
spec:
  selector:
    app: api-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
