# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-service
  labels:
    app: app-service
spec:
  replicas: 1
  selector:
    matchLabels:  
      app: app-service
  template:
    metadata:
      labels:
        app: app-service
    spec:
      nodeSelector:
        type: worker1
      containers:
        - name: app-container
          image: myfirstcontainerdemo.azurecr.io/react-app:v_${{github.run_number}}
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"     
              memory: "200Mi" 
            limits:
              cpu: "150m"        
              memory: "250Mi"  
              
---

# Expose
apiVersion: v1
kind: Service
metadata:
  name: app-expose
spec:
  selector:
    app: app-service
  ports:
  - protocol: TCP
    port: 81  # Expose the service on port 80
    targetPort: 80  # Map to the container's port 80
  type: LoadBalancer

---

# Horizontal Pod Autoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-service
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70  # scale based on 70% CPU utilization
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75  # scale based on 75% memory utilization