# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-service
  labels:
    app: app-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-service
  template:
    metadata:
      labels:
        app: app-service
    spec:
      nodeSelector:
        type: worker1
      containers:
      - name: app-container
        # image: myfirstcontainerdemo.azurecr.io/react-app:v_17
        image: myfirstcontainerdemo.azurecr.io/react-app:<IMAGE_TAG>
        ports:
        - containerPort: 80  # Expose port 80, matching Nginx's port
        # resources:
        #   requests:
        #     cpu: "500m"
        #     memory: "256Mi"
        #   limits:
        #     cpu: "1"
        #     memory: "512Mi"
---

# Expose
apiVersion: v1
kind: Service
metadata:
  name: app-expose
spec:
  selector:
    app: app-service
  ports:
  - protocol: TCP
    port: 80  # Expose the service on port 80
    targetPort: 80  # Map to the container's port 80
  type: LoadBalancer