apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"  # Set to true if using pod identity
    useVMManagedIdentity: "true"  # Set to true if using managed identity
    userAssignedIdentityID: "145358ec-7734-40db-b15344-3caf47450e398a" # Optional for system-assigned identity
    keyvaultName: "EGKeyVault01"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: "DbName"
          objectType: secret
          objectVersion: ""
    tenantId: "d2805df3-d561-4de9-b00f-a16832c7a5b4"
