apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-provider
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          
    userAssignedIdentityID: "8b199bce-14bc-4a9c-9a3b-ad5b837b0e86"  
    keyvaultName: "EGKeyVault01"
    cloudName: "AzureCloud"                          
    objects: |
      array:
        - |
          objectName: "dbname"
          objectType: secret
          objectVersion: ""
    tenantId: "d2805df3-d561-4de9-b00f-a16832c7a5b4"
