apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "false" # Disable Pod Identity
    useVMManagedIdentity: "false" # Disable Managed Identity
    clientID: {{AZURE_CLIENTID}} # Client ID of the Service Principal
    clientSecret: {{AZURE_CLIENTSECRET}} # Secret of the Service Principal
    keyvaultName: "EGKeyVault01" # Name of your Key Vault
    cloudName: "AzureCloud"
    objects: |
      array:
        - |
          objectName: dbname
          objectType: secret
        - |
          objectName: adminid
          objectType: secret
    tenantId: {{AZURE_CLIENT_TENANT}} # Tenant ID of the Service Principal