name: AKS APP DEPLOYMENT

on:
  push:
    branches:
      - main
    paths:
      - 'APP/**'
      - 'manifests/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build-and-push-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_NAME }}
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}
      - run: |
            docker build -t ${{ secrets.ACR_NAME }}/react-app:v_${{ github.run_number }} ./APP
            docker push ${{ secrets.ACR_NAME }}/react-app:v_${{ github.run_number }}

       # Set the target AKS cluster.
      - uses: Azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: EGClusterTest
          resource-group: DemoEG
          
      - uses: Azure/k8s-create-secret@v1
        with:
          container-registry-url: ${{ secrets.ACR_NAME }}
          container-registry-username: ${{ secrets.AZURE_CLIENT_ID }}
          container-registry-password: ${{ secrets.AZURE_CLIENT_SECRET }}
          secret-name: my-secret2

      # Inject GitHub Actions secrets into secrets.yml with base64 encoding
      - name: Update secrets.yml with GitHub Secrets
        run: |
          # Encode the secrets in base64 and replace placeholders in secrets.yml
          sed -i "s|{{SECRET_CONN_STRING}}|$(echo -n ${{ secrets.CONN_STRING }} | base64)|g" manifests/secrets.yml
          sed -i "s|{{SECRET_DB_NAME}}|$(echo -n ${{ secrets.DB_NAME }} | base64)|g" manifests/secrets.yml
          sed -i "s|{{SECRET_DB_PASSWORD}}|$(echo -n ${{ secrets.DB_PASSWORD }} | base64)|g" manifests/secrets.yml

      - uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            manifests/secrets.yml
            manifests/app_deployment.yml
          images: |
            ${{ secrets.ACR_NAME }}/react-app:v_${{ github.run_number }}
          imagepullsecrets: |
            my-secret2
