name: Build and Push Docker Images

on:
  push:
    branches:
      - main 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      ACR_NAME: ${{ secrets.ACR_NAME }}
      ACR_URL: ${{ secrets.ACR_NAME }}.azurecr.io

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Log in to Azure Container Registry
        run: |
          az login --service-principal \
            --username ${{ secrets.AZURE_CLIENT_ID }} \
            --password ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}
          az acr login --name ${{ env.ACR_NAME }}

      - name: Build and push frontend image
        run: |
          LOWER_ACR_URL=$(echo "${{ env.ACR_URL }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ${LOWER_ACR_URL}/react-app:latest ./APP
          docker push ${LOWER_ACR_URL}/react-app:latest

      - name: Build and push API image 
        run: |
          LOWER_ACR_URL=$(echo "${{ env.ACR_URL }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ${LOWER_ACR_URL}/demok8sapi:latest ./API
          docker push ${LOWER_ACR_URL}/demok8sapi:latest
