name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      ACR_URL: ${{ secrets.ACR_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        run: |
          az login --service-principal \
            --username ${{ secrets.AZURE_CLIENT_ID }} \
            --password ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}
          az acr login --name ${{ env.ACR_URL }}

      - name: Build and push frontend image
        run: |
          docker build -t ${{ env.ACR_URL }}/frontend:latest ./frontend
          docker push ${{ env.ACR_URL }}/frontend:latest

      - name: Build and push API image
        run: |
          docker build -t ${{ env.ACR_URL }}/api:latest ./api
          docker push ${{ env.ACR_URL }}/api:latest

      - name: Build and push service image
        run: |
          docker build -t ${{ env.ACR_URL }}/service:latest ./service
          docker push ${{ env.ACR_URL }}/service:latest
