name: Build and Push Images

on: 
  workflow_dispatch: 
  push:
    - main

jobs:
  build-and-push: 
    runs-on: ubuntu-latest
    env:
      ACR_NAME: ${{secrets.ACR_NAME}}
      ACR_URL: ${{secrets.ACR_NAME}}.azurecr.io

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker
        run: echo Login
