name: Build and Push Docker Images

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  # Job 1: Update Secrets in YAML
  update-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Inject GitHub Actions secrets into secrets.yaml
      - name: Update secrets.yaml with GitHub Secrets
        run: |
          # Replace placeholders in secrets.yaml with GitHub secrets
          sed -i "s/{{SECRET_CONN_STRING}}/${{ secrets.CONN_STRING }}/g" manifests/secrets.yaml
          sed -i "s/{{SECRET_DB_NAME}}/${{ secrets.DB_NAME }}/g" manifests/secrets.yaml
          sed -i "s/{{SECRET_DB_PASSWORD}}/${{ secrets.DB_PASSWORD }}/g" manifests/secrets.yaml

  build-and-push-api:
    if: >
      github.event_name == 'workflow_dispatch' || 
      contains(join(github.event.commits.*.modified, ','), 'main/API') || 
      contains(join(github.event.commits.*.modified, ','), 'main/manifests')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_NAME }}
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}
      - run: |
            docker build -t ${{ secrets.ACR_NAME }}/demok8sapi:v_${{ github.run_number }} ./API
            docker push ${{ secrets.ACR_NAME }}/demok8sapi:v_${{ github.run_number }}

       # Set the target AKS cluster.
      - uses: Azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: EGClusterTest
          resource-group: DemoEG
          
      - uses: Azure/k8s-create-secret@v1
        with:
          container-registry-url: ${{ secrets.ACR_NAME }}
          container-registry-username: ${{ secrets.AZURE_CLIENT_ID }}
          container-registry-password: ${{ secrets.AZURE_CLIENT_SECRET }}
          secret-name: my-secret

      - uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            manifests/secrets.yaml
            manifests/api_deployment.yml
          images: |
            ${{ secrets.ACR_NAME }}/demok8sapi:v_${{ github.run_number }}
          imagepullsecrets: |
            my-secret

  build-and-push-app:
    if: >
      github.event_name == 'workflow_dispatch' || 
      contains(join(github.event.commits.*.modified, ','), 'main/APP') || 
      contains(join(github.event.commits.*.modified, ','), 'main/manifests')

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_NAME }}
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}
      - run: |
            docker build -t ${{ secrets.ACR_NAME }}/react-app:v_${{ github.run_number }} ./APP
            docker push ${{ secrets.ACR_NAME }}/react-app:v_${{ github.run_number }}

       # Set the target AKS cluster.
      - uses: Azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: EGClusterTest
          resource-group: DemoEG
          
      - uses: Azure/k8s-create-secret@v1
        with:
          container-registry-url: ${{ secrets.ACR_NAME }}
          container-registry-username: ${{ secrets.AZURE_CLIENT_ID }}
          container-registry-password: ${{ secrets.AZURE_CLIENT_SECRET }}
          secret-name: my-secret2

      - uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            manifests/secrets.yaml
            manifests/app_deployment.yml
          images: |
            ${{ secrets.ACR_NAME }}/react-app:v_${{ github.run_number }}
          imagepullsecrets: |
            my-secret2
