name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - 'main/api/**'
      - 'main/app/**'
      - 'main/manifests/**'
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    env:
      ACR_NAME: ${{ secrets.ACR_NAME }}
      ACR_URL: ${{ secrets.ACR_NAME }}.azurecr.io

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Log in to Azure
        run: |
          az login --service-principal \
            --username ${{ secrets.AZURE_CLIENT_ID }} \
            --password ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}
          az acr login --name ${{ env.ACR_NAME }}

      - name: Get Kubernetes credentials
        run: |
          az aks get-credentials \
            --resource-group DemoEG \
            --name EGClusterTest \
            --overwrite-existing

  build-and-push-api:
    needs: prepare
    if: github.event_name == 'workflow_dispatch' || contains(github.event.commits.*.modified, 'main/api') || contains(github.event.commits.*.modified, 'main/manifests')
    runs-on: ubuntu-latest
    env:
      ACR_NAME: ${{ secrets.ACR_NAME }}
      ACR_URL: ${{ secrets.ACR_NAME }}.azurecr.io

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        run: |
          az login --service-principal \
            --username ${{ secrets.AZURE_CLIENT_ID }} \
            --password ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}
          az acr login --name ${{ env.ACR_NAME }}

      - name: Build and push API image
        run: |
          docker build -t ${{ env.ACR_URL }}/demok8sapi:v_${{ github.run_number }} ./API
          docker push ${{ env.ACR_URL }}/demok8sapi:v_${{ github.run_number }}
          
      - name: Update Deployment YAML
        run: |
          sed -i "s|<IMAGE_TAG>|v_${{ github.run_number }}|g" manifests/api_deployment.yaml

      - name: Deploy API to AKS
        run: |
          kubectl apply -f manifests/api_deployment.yaml

  build-and-push-app:
    needs: prepare
    if: github.event_name == 'workflow_dispatch' || contains(github.event.commits.*.modified, 'main/app') || contains(github.event.commits.*.modified, 'main/manifests')
    runs-on: ubuntu-latest
    env:
      ACR_NAME: ${{ secrets.ACR_NAME }}
      ACR_URL: ${{ secrets.ACR_NAME }}.azurecr.io

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        run: |
          az login --service-principal \
            --username ${{ secrets.AZURE_CLIENT_ID }} \
            --password ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}
          az acr login --name ${{ env.ACR_NAME }}

      - name: Build and push APP image
        run: |
          docker build -t ${{ env.ACR_URL }}/react-app:v_${{ github.run_number }} ./APP
          docker push ${{ env.ACR_URL }}/react-app:v_${{ github.run_number }}

      - name: Update App Deployment YAML
        run: |
          sed -i "s|<IMAGE_TAG>|v_${{ github.run_number }}|g" manifests/app_deployment.yaml

      - name: Deploy App to AKS
        run: |
          kubectl apply -f manifests/app_deployment.yaml