# name: Build and Push Images

# on: 
#   push: 
#     branches:
#       - main

# jobs:
#   build-and-push: 
#     runs-on: ubuntu-latest
#     env:
#       ACR_NAME: ${{secrets.ACR_NAME}}
#       ACR_URL: ${{secrets.ACR_NAME}}.azurecr.io

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Login to Docker
#         run: echo Login
# =================================================================

name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      ACR_NAME: ${{ secrets.ACR_NAME }}
      ACR_URL: ${{ secrets.ACR_NAME }}.azurecr.io

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          
      - name: Log in to Azure Container Registry
        run: |
          echo ${{ secrets.AZURE_CLIENT_ID }}
          echo ${{ secrets.AZURE_CLIENT_SECRET }}
          az login --service-principal \
            --username ${{ secrets.AZURE_CLIENT_ID }} \
            --password ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}
          echo Login success 
          echo iniated
          az acr login --name ${{ env.ACR_NAME }}
          echo success
          
      - name: Build and push frontend image
        run: |
          docker build -t ${{ env.ACR_URL }}/samples/react-app:latest ./APP
          docker push ${{ env.ACR_URL }}/samples/react-app:latest
          
      - name: Build and push API image
        run: |
          docker build -t ${{ env.ACR_URL }}/samples/demok8sapi:latest ./API
          docker push ${{ env.ACR_URL }}/samples/demok8sapi:latest

          
